import type { CareerV2, Fixture, GameResult, Player, Team, TeamRecord } from './types'
import { addStats, blankStats } from './types'
export { simulateFixture } from './matchEngine'

const dateAt = (round: number, seasonNumber: number) => { const date = new Date(`${2025 + seasonNumber}-10-20T12:00:00Z`); date.setUTCDate(date.getUTCDate() + Math.floor(round * 2.05)); return date.toISOString().slice(0, 10) }

/** Circle-derived schedule: 82 rounds × 15 games = 1,230 games and exactly 82 fixtures per team. */
export function createLeagueSchedule(teams: Team[], seasonNumber = 1): Fixture[] {
  const ring = teams.map((team) => team.abbr); const fixtures: Fixture[] = []
  for (let round = 0; round < 82; round += 1) { const shift = round % ring.length; const rotated = ring.map((_, index) => ring[(index + shift) % ring.length]); for (let pair = 0; pair < 15; pair += 1) { const left = rotated[pair]; const right = rotated[29 - pair]; const home = (round + pair) % 2 === 0 ? left : right; const away = home === left ? right : left; fixtures.push({ id: `s${seasonNumber}-${round + 1}-${pair + 1}`, date: dateAt(round, seasonNumber), round: round + 1, home, away, status: 'scheduled' }) } }
  return fixtures
}
export const baseStandings = (teams: Team[]): Record<string, TeamRecord> => Object.fromEntries(teams.map((team) => [team.abbr, { team: team.abbr, wins: 0, losses: 0, pf: 0, pa: 0, streak: 0 }]))
export function applyResults(career: CareerV2, games: GameResult[]): CareerV2 {
  const next = structuredClone(career)
  for (const game of games) { const fixture = next.fixtures.find((candidate) => candidate.id === game.fixtureId); if (!fixture || fixture.status === 'played') continue; fixture.status = 'played'; fixture.homeScore = game.homeScore; fixture.awayScore = game.awayScore; fixture.gameId = game.id; next.results[game.id] = game; const home = next.standings[game.home]; const away = next.standings[game.away]; home.pf += game.homeScore; home.pa += game.awayScore; away.pf += game.awayScore; away.pa += game.homeScore; const homeWin = game.homeScore > game.awayScore; home.wins += homeWin ? 1 : 0; home.losses += homeWin ? 0 : 1; away.wins += homeWin ? 0 : 1; away.losses += homeWin ? 1 : 0; home.streak = homeWin ? Math.max(1, home.streak + 1) : Math.min(-1, home.streak - 1); away.streak = homeWin ? Math.min(-1, away.streak - 1) : Math.max(1, away.streak + 1); Object.entries(game.box).forEach(([id, line]) => { const playerId = Number(id); next.playerStats[playerId] = addStats(next.playerStats[playerId] ?? blankStats(), line); const playerModel = next.playerModels[playerId]; if (playerModel) { playerModel.readiness = Math.max(45, playerModel.readiness - Math.round(line.min / 18)); playerModel.morale = Math.max(25, Math.min(99, playerModel.morale + ((game.home === playerModelTeam(playerId, game, next) ? homeWin : !homeWin) ? 1 : -1))) } }); for (const injury of game.injuries ?? []) { next.health[injury.playerId] = {...(next.health[injury.playerId] ?? {fatigue:25,condition:88}),injury:`${injury.diagnosis} · ${injury.recoveryGames} jogos`,condition:Math.min(next.health[injury.playerId]?.condition ?? 88,72)}; const playerModel = next.playerModels[injury.playerId]; if (playerModel) playerModel.readiness = Math.min(playerModel.readiness,58) } if (game.home === next.teamAbbr || game.away === next.teamAbbr) { next.record = { wins: next.standings[next.teamAbbr].wins, losses: next.standings[next.teamAbbr].losses }; next.currentDate = game.playedAt; Object.entries(next.health).forEach(([id, status]) => { const minutes = game.box[id]?.min ?? 0; status.fatigue = Math.min(100, status.fatigue + Math.round(minutes / 7)); status.condition = Math.max(55, status.condition - Math.round(minutes / 18)) }) } }
  next.simulationLog.push(`${games[0]?.playedAt ?? next.currentDate}: ${games.length} jogos processados com engine ${next.engineVersion}.`); return next
}
const playerModelTeam = (playerId: number, game: GameResult, career: CareerV2) => career.economy.contracts[playerId]?.team || (game.box[playerId] ? game.home : game.away)
export const standingsSorted = (records: Record<string, TeamRecord>) => Object.values(records).sort((a, b) => b.wins - a.wins || (b.pf - b.pa) - (a.pf - a.pa))
export const nextTeamFixture = (career: CareerV2) => career.fixtures.find((fixture) => fixture.status === 'scheduled' && (fixture.home === career.teamAbbr || fixture.away === career.teamAbbr))
export function createPlayoffBracket(career: CareerV2, teams: Team[]) { const series = []; for (const conference of ['East','West']) { const seeds = standingsSorted(career.standings).filter((row) => teams.find((team) => team.abbr === row.team)?.conference.startsWith(conference)).slice(0, 8); for (let index = 0; index < 4; index += 1) series.push({ id: `po-${conference}-${index + 1}-s${career.seasonNumber}`, conference, round: 1, higherSeed: seeds[index]?.team ?? 'TBD', lowerSeed: seeds[7 - index]?.team ?? 'TBD', higherWins: 0, lowerWins: 0 }) } return series }
export function rosterCompliance(players: Player[], economy: CareerV2['economy'], team: string) { const roster = players.filter((player) => economy.contracts[player.id]?.team === team && economy.contracts[player.id]?.status === 'active'); return { count: roster.length, valid: roster.length >= 12 && roster.length <= 18, reasons: roster.length < 12 ? ['Elenco abaixo do mínimo do ruleset.'] : roster.length > 18 ? ['Elenco acima do máximo do ruleset.'] : [] } }
