import { addStats, blankStats, type AdvancedTeamStats, type CareerV2, type Fixture, type GameEvent, type GameResult, type Health, type LineupStat, type Player, type PlayerModel, type RotationEntry, type ShotChartPoint, type StatLine } from './types'
import { createPlayerModel, ENGINE_VERSION, randomFromSeed } from './simulationData'

type Side = { abbr: string; players: Player[]; lineup: Player[]; bench: Player[]; tactics: CareerV2['tactics'] }
const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value))
const weighted = <T,>(items: T[], weight: (item: T) => number, random: () => number) => { const total = items.reduce((sum, item) => sum + Math.max(.01, weight(item)), 0); let cursor = random() * total; for (const item of items) { cursor -= Math.max(.01, weight(item)); if (cursor <= 0) return item } return items[items.length - 1] }
const sumTeam = (box: Record<number, StatLine>, side: Side) => side.players.map((player) => box[player.id]).reduce(addStats, blankStats())
const checksum = (value: string) => { let hash = 0; for (const char of value) hash = ((hash << 5) - hash + char.charCodeAt(0)) | 0; return Math.abs(hash).toString(36) }

export function simulateFixture(fixture: Fixture, players: Player[], userTeam: string, rotation: RotationEntry[], tactics: CareerV2['tactics'], includeEvents = true, suppliedModels?: Record<number, PlayerModel>, health: Record<number, Health> = {}): GameResult {
  const seed = `${ENGINE_VERSION}:${fixture.id}:${fixture.round}:${JSON.stringify(tactics)}`; const random = randomFromSeed(seed)
  const models = suppliedModels ?? Object.fromEntries(players.map((player) => [player.id, createPlayerModel(player)]))
  const buildSide = (abbr: string): Side => { const teamPlayers = players.filter((player) => player.team === abbr).sort((a, b) => b.overall - a.overall).slice(0, 12); const ordered = abbr === userTeam && rotation.length ? [...teamPlayers].sort((a, b) => (rotation.find((entry) => entry.playerId === b.id)?.minutes ?? 0) - (rotation.find((entry) => entry.playerId === a.id)?.minutes ?? 0)) : teamPlayers; return { abbr, players: ordered, lineup: ordered.slice(0, 5), bench: ordered.slice(5), tactics: abbr === userTeam ? tactics : { pace: 42 + Math.round(random() * 30), offense: random() > .5 ? '5-out' : 'Equilibrado', defense: random() > .65 ? 'Proteção de aro' : 'Trocas seletivas', rebounding: random() > .5 ? 'Proteção de aro' : 'Ataque ao rebote', focus: random() > .45 ? 'Ataque ao aro' : 'Bola de três' } } }
  const home = buildSide(fixture.home); const away = buildSide(fixture.away); const sides: Record<string, Side> = { [home.abbr]: home, [away.abbr]: away }; const opponent = (team: string) => team === home.abbr ? away : home
  const box: Record<number, StatLine> = Object.fromEntries([...home.players, ...away.players].map((player) => [player.id, blankStats()])); const events: GameEvent[] = []; const shots: ShotChartPoint[] = []; const injuries: NonNullable<GameResult['injuries']> = []; const lineups: LineupStat[] = []; const score = { [home.abbr]: 0, [away.abbr]: 0 }; const teamFouls = { [home.abbr]: 0, [away.abbr]: 0 }; let seq = 0
  const event = (period: number, clock: number, team: string, playerId: number, type: GameEvent['type'], text: string, x = 50, y = 50, shotClock = 24) => { if (includeEvents) events.push(Object.freeze({ id: `${fixture.id}-e${seq}`, seq: seq++, period, clock, shotClock, team, playerId, type, text, homeScore: score[home.abbr], awayScore: score[away.abbr], x, y })) }
  const model = (player: Player) => models[player.id] ?? createPlayerModel(player)
  const chooseShooter = (side: Side) => weighted(side.lineup, (player) => model(player).offense + (model(player).roles.includes('Primary') ? 25 : 0), random)
  const substitute = (side: Side, period: number, clock: number) => { if (!side.bench.length) return; const tired = [...side.lineup].sort((a, b) => (health[b.id]?.fatigue ?? 20) + box[b.id].pf * 13 - ((health[a.id]?.fatigue ?? 20) + box[a.id].pf * 13))[0]; const replacement = side.bench.shift(); if (!replacement || !tired || box[tired.id].pf < 4 && random() > .16) { if (replacement) side.bench.unshift(replacement); return } side.lineup = side.lineup.map((player) => player.id === tired.id ? replacement : player); side.bench.push(tired); event(period, clock, side.abbr, replacement.id, 'substitution', `${replacement.name} entra no lugar de ${tired.name}.`) }
  const playPossession = (attacking: Side, defending: Side, period: number, clock: number) => {
    const shooter = chooseShooter(attacking); const shooterModel = model(shooter); const defender = weighted(defending.lineup, (player) => model(player).defense, random); const defenderModel = model(defender)
    const paceFactor = (attacking.tactics.pace - 50) / 100; const duration = clamp(Math.round(15 - paceFactor * 5 + random() * 7 - 3.5), 5, 24); const threeBias = (attacking.tactics.focus === 'Bola de três' ? .12 : 0) + (attacking.tactics.offense === '5-out' ? .08 : 0); const three = random() < clamp(shooterModel.tendencies.three / 120 + threeBias, .18, .66); const x = three ? 13 + random() * 74 : 35 + random() * 30; const y = three ? 7 + random() * 86 : 28 + random() * 44
    const currentFatigue = health[shooter.id]?.fatigue ?? 18; const injuryChance = .00022 + Math.max(0, 76 - shooterModel.durability) / 90_000 + currentFatigue / 230_000
    if (!injuries.some((item) => item.playerId === shooter.id) && random() < injuryChance) { const severe = random() < .16; const diagnosis = severe ? 'Entorse moderada (SIM)' : 'Contusão leve (SIM)'; const recoveryGames = severe ? 8 + Math.floor(random() * 15) : 1 + Math.floor(random() * 5); injuries.push({playerId:shooter.id,diagnosis,recoveryGames}); event(period,clock,attacking.abbr,shooter.id,'injury',`${shooter.name} deixa a quadra: ${diagnosis}.`,x,y,24); const replacement = attacking.bench.shift(); if (replacement) attacking.lineup = attacking.lineup.map((player) => player.id === shooter.id ? replacement : player); return duration }
    const stealChance = .045 + defenderModel.defense / 2400 + shooterModel.tendencies.turnover / 2500; if (random() < stealChance) { box[shooter.id].tov += 1; box[defender.id].stl += 1; event(period, clock, defending.abbr, defender.id, 'steal', `${defender.name} antecipa o passe e rouba a bola.`, x, y, Math.max(1, 24 - duration)); return duration }
    const foulChance = .055 + shooterModel.tendencies.foulDraw / 1800; if (random() < foulChance) { box[defender.id].pf += 1; teamFouls[defending.abbr] += 1; event(period, clock, defending.abbr, defender.id, 'foul', `${defender.name} comete a falta em ${shooter.name}.`, x, y, Math.max(1, 24 - duration)); if (teamFouls[defending.abbr] >= 5 || random() < .42) { const attempts = three && random() < .12 ? 3 : 2; for (let attempt = 0; attempt < attempts; attempt += 1) { box[shooter.id].fta += 1; const made = random() < clamp((shooterModel.shooting - 18) / 100, .52, .92); if (made) { box[shooter.id].ftm += 1; box[shooter.id].pts += 1; score[attacking.abbr] += 1 } event(period, clock, attacking.abbr, shooter.id, 'ft', `${shooter.name} ${made ? 'converte' : 'erra'} o lance livre ${attempt + 1}/${attempts}.`, 50, 50, 0) } } return duration }
    const contest = Math.max(0, defenderModel.defense - 55) * .0015 + (defending.tactics.defense === 'Pressão na bola' && three ? .025 : 0) + (defending.tactics.defense === 'Proteção de aro' && !three ? .035 : 0); const skill = three ? shooterModel.shooting : (shooterModel.finishing * .62 + shooterModel.shooting * .38); const makeChance = clamp((three ? .31 : .47) + (skill - 60) * .0045 - contest + (shooterModel.iq - 65) * .0012, three ? .27 : .39, three ? .54 : .73); const made = random() < makeChance; const value = three ? 3 : 2; const line = box[shooter.id]; line.fga += 1; if (three) line.tpa += 1
    if (made) { line.fgm += 1; line.pts += value; score[attacking.abbr] += value; if (three) line.tpm += 1; const assister = weighted(attacking.lineup.filter((player) => player.id !== shooter.id), (player) => model(player).playmaking + model(player).tendencies.pass, random); if (assister && random() < clamp(.38 + model(assister).playmaking / 210, .45, .84)) box[assister.id].ast += 1 } else if (!three && random() < defenderModel.defense / 900) { box[defender.id].blk += 1; event(period, clock, defending.abbr, defender.id, 'block', `${defender.name} bloqueia a tentativa de ${shooter.name}.`, x, y, Math.max(1, 24 - duration)) }
    if (includeEvents) shots.push({ team: attacking.abbr, playerId: shooter.id, x, y, made, value: value as 2 | 3, period }); event(period, clock, attacking.abbr, shooter.id, made ? (three ? 'made3' : 'made2') : (three ? 'miss3' : 'miss2'), `${shooter.name} ${made ? 'converte' : 'não converte'} ${three ? 'de três pontos' : 'da zona de dois'}.`, x, y, Math.max(1, 24 - duration))
    if (!made) { const offensiveChance = .19 + (attacking.tactics.rebounding === 'Ataque ao rebote' ? .09 : 0); const reboundSide = random() < offensiveChance ? attacking : defending; const rebounder = weighted(reboundSide.lineup, (player) => model(player).rebounding, random); box[rebounder.id].reb += 1; event(period, clock, reboundSide.abbr, rebounder.id, 'rebound', `${rebounder.name} fica com o rebote ${reboundSide === attacking ? 'ofensivo' : 'defensivo'}.`, x, y, 24) }
    return duration
  }
  const playPeriod = (period: number, startingClock: number) => { teamFouls[home.abbr] = 0; teamFouls[away.abbr] = 0; let clock = startingClock; let possession = period % 2 === 1 ? away : home; event(period, clock, possession.abbr, possession.lineup[0]?.id ?? 0, 'period', `Início do ${period <= 4 ? `${period}º período` : `OT${period - 4}`}.`); while (clock > 0) { const duration = playPossession(possession, opponent(possession.abbr), period, clock); clock = Math.max(0, clock - duration); if (clock > 80 && random() < .045) substitute(possession, period, clock); if (clock > 90 && Math.abs(score[home.abbr] - score[away.abbr]) > 11 && random() < .022) event(period, clock, opponent(possession.abbr).abbr, opponent(possession.abbr).lineup[0]?.id ?? 0, 'timeout', `${opponent(possession.abbr).abbr} pede tempo para ajustar a defesa.`); possession = opponent(possession.abbr) } }
  for (let period = 1; period <= 4; period += 1) playPeriod(period, 720); let overtime = 0; while (score[home.abbr] === score[away.abbr] && overtime < 4) { overtime += 1; playPeriod(4 + overtime, 300) }
  for (const side of [home, away]) { side.players.forEach((player, index) => { const rotationMinutes = side.abbr === userTeam ? rotation.find((entry) => entry.playerId === player.id)?.minutes : undefined; const baseMinutes = rotationMinutes ?? [35,34,32,30,28,22,19,16,13,11,0,0][index] ?? 0; box[player.id].gp = baseMinutes > 0 ? 1 : 0; box[player.id].gs = index < 5 ? 1 : 0; box[player.id].min = Math.round(baseMinutes * (1 + overtime * .085)) }); const pointsFor = score[side.abbr]; const pointsAgainst = score[opponent(side.abbr).abbr]; lineups.push({ team: side.abbr, playerIds: side.lineup.map((player) => player.id), minutes: 12 + overtime * 2, pointsFor: Math.round(pointsFor * .27), pointsAgainst: Math.round(pointsAgainst * .27), netRating: Math.round(((pointsFor - pointsAgainst) / Math.max(1, pointsFor + pointsAgainst)) * 200) / 2 }) }
  const teamTotals = { [home.abbr]: sumTeam(box, home), [away.abbr]: sumTeam(box, away) }; const advanced: Record<string, AdvancedTeamStats> = {}
  for (const side of [home, away]) { const totals = teamTotals[side.abbr]; const rival = teamTotals[opponent(side.abbr).abbr]; const possessions = Math.max(1, totals.fga + .44 * totals.fta - totals.reb * .18 + totals.tov); advanced[side.abbr] = { possessions: Math.round(possessions), offensiveRating: Math.round(score[side.abbr] / possessions * 1000) / 10, defensiveRating: Math.round(score[opponent(side.abbr).abbr] / possessions * 1000) / 10, pace: Math.round(possessions * 10) / 10, effectiveFg: Math.round((totals.fgm + .5 * totals.tpm) / Math.max(1, totals.fga) * 1000) / 10, trueShooting: Math.round(score[side.abbr] / Math.max(1, 2 * (totals.fga + .44 * totals.fta)) * 1000) / 10, turnoverRate: Math.round(totals.tov / possessions * 1000) / 10, offensiveReboundRate: Math.round(totals.reb / Math.max(1, totals.reb + rival.reb) * 1000) / 10, freeThrowRate: Math.round(totals.fta / Math.max(1, totals.fga) * 1000) / 10 } }
  const result: GameResult = { id: `game-${fixture.id}`, fixtureId: fixture.id, home: home.abbr, away: away.abbr, homeScore: score[home.abbr], awayScore: score[away.abbr], playedAt: fixture.date, events, box, teamTotals, seed, engineVersion: ENGINE_VERSION, overtime, advanced, lineups, shotChart: shots, injuries, checksum: checksum(`${seed}:${score[home.abbr]}:${score[away.abbr]}:${JSON.stringify(box)}`) }
  return Object.freeze(result)
}
