import { applyResults, baseStandings, createLeagueSchedule, createPlayoffBracket, simulateFixture, standingsSorted } from './league'
import { blankStats, type CareerV2, type Player, type PlayoffSeries, type Prospect, type Team } from './types'
import { createPlayerModel, developModels, generateDraftClass, randomFromSeed } from './simulationData'

const universePlayers = (career: CareerV2, players: Player[]) => [...players, ...career.generatedPlayers].filter((player) => !career.retiredPlayerIds.includes(player.id)).map((player) => ({ ...player, team: career.economy.contracts[player.id]?.team ?? player.team }))
export function simulateRounds(career: CareerV2, players: Player[], roundCount: number) {
  const rounds = [...new Set(career.fixtures.filter((fixture) => fixture.status === 'scheduled').map((fixture) => fixture.round))].sort((a,b) => a-b).slice(0, roundCount)
  const activePlayers = universePlayers(career, players); const games = career.fixtures.filter((fixture) => fixture.status === 'scheduled' && rounds.includes(fixture.round)).map((fixture) => simulateFixture(fixture, activePlayers, career.teamAbbr, career.rotation, career.tactics, false, career.playerModels, career.health)); const next = applyResults(career, games)
  next.news.unshift({ id: `fast-${Date.now()}`, date: next.currentDate, category: 'league', title: `${rounds.length} rodada(s) simulada(s)`, body: `${games.length} partidas foram processadas pela mesma engine determinística, sem renderização.` })
  return next
}

function playSeries(career: CareerV2, series: PlayoffSeries, players: Player[], round: number): PlayoffSeries {
  const activePlayers = universePlayers(career, players); let higherWins = 0; let lowerWins = 0; let gameIndex = 0
  while (higherWins < 4 && lowerWins < 4) { const higherHome = gameIndex % 4 < 2; const fixture = { id: `${series.id}-g${gameIndex + 1}`, date: career.currentDate, round: 82 + round, home: higherHome ? series.higherSeed : series.lowerSeed, away: higherHome ? series.lowerSeed : series.higherSeed, status: 'scheduled' as const }; const result = simulateFixture(fixture, activePlayers, career.teamAbbr, career.rotation, career.tactics, false, career.playerModels, career.health); career.results[result.id] = result; const higherScore = result.home === series.higherSeed ? result.homeScore : result.awayScore; const lowerScore = result.home === series.lowerSeed ? result.homeScore : result.awayScore; if (higherScore > lowerScore) higherWins += 1; else lowerWins += 1; gameIndex += 1 }
  return { ...series, higherWins, lowerWins, winner: higherWins === 4 ? series.higherSeed : series.lowerSeed }
}
export function simulatePostseason(career: CareerV2, players: Player[], teams: Team[]) {
  const next = structuredClone(career); let roundSeries = createPlayoffBracket(next, teams).map((series) => playSeries(next, series, players, 1)); const allSeries: PlayoffSeries[] = [...roundSeries]
  for (let round = 2; round <= 3; round += 1) { const nextSeries: PlayoffSeries[] = []; for (const conference of ['East','West']) { const winners = roundSeries.filter((series) => series.conference === conference).map((series) => series.winner!).filter(Boolean); for (let index = 0; index < winners.length / 2; index += 1) nextSeries.push({ id: `po-${conference}-r${round}-${index + 1}`, conference, round, higherSeed: winners[index * 2], lowerSeed: winners[index * 2 + 1], higherWins: 0, lowerWins: 0 }) } roundSeries = nextSeries.map((series) => playSeries(next, series, players, round)); allSeries.push(...roundSeries) }
  const finalists = roundSeries.map((series) => series.winner!).filter(Boolean); const finals = playSeries(next, { id: `po-finals-s${next.seasonNumber}`, conference: 'Finals', round: 4, higherSeed: finalists[0], lowerSeed: finalists[1], higherWins: 0, lowerWins: 0 }, players, 4); allSeries.push(finals); next.playoffs = allSeries; next.seasonArchives.push({ season: `${2025 + next.seasonNumber}-${String(26 + next.seasonNumber).slice(-2)}`, champion: finals.winner, standings: standingsSorted(next.standings), awards: { champion: finals.winner ?? 'TBD' }, draftClassId: `draft-${2026 + next.seasonNumber}` }); next.news.unshift({ id: `champion-${next.seasonNumber}`, date: next.currentDate, category: 'league', title: `${finals.winner} conquista o título`, body: `Playoffs completos simulados pela engine ${next.engineVersion}.` }); return next
}
const makeRookie = (prospect: Prospect, season: number, pick: number, team: string): Player => {
  const id = 9_000_000 + season * 100 + pick
  const [firstName, ...rest] = prospect.name.split(' '); const lastName = rest.join(' ')
  return { id, firstName, lastName, name: prospect.name, slug: `dev-${season}-${pick}`, teamId: 0, team, jersey: String((pick * 3) % 55), position: prospect.position, height: prospect.position === 'C' ? '6-11' : prospect.position === 'PG' ? '6-3' : '6-7', weight: prospect.position === 'C' ? '245 lbs' : '210 lbs', college: 'SIMULATION Draft Class', country: 'DEV', overall: Math.max(64, 82 - Math.floor(pick / 2)), headshot: 'assets/nba/players/generated.svg' }
}

/** Complete offseason: options/expiries, deterministic retirement, 30-pick draft and AI roster balancing. */
export function advanceOffseason(career: CareerV2, players: Player[], teams: Team[]) {
  const next = structuredClone(career); const endingSeason = next.seasonNumber
  Object.values(next.economy.contracts).forEach((contract) => { if (contract.status !== 'active') return; contract.years -= 1; if (contract.years <= 0) { contract.status = 'free-agent'; contract.team = 'FA'; contract.years = 0 } })
  next.playerModels = developModels(next.playerModels, endingSeason)
  for (const model of Object.values(next.playerModels)) { const random = randomFromSeed(`retire-${endingSeason}-${model.playerId}`); if (model.age >= 38 && random() < Math.min(.92, .24 + (model.age - 38) * .17)) { next.retiredPlayerIds.push(model.playerId); const contract = next.economy.contracts[model.playerId]; if (contract) { contract.status = 'waived'; contract.team = 'RET'; contract.years = 0 } } }
  const order = Object.values(next.standings).sort((a,b) => a.wins - b.wins || a.pf - a.pa).map((row) => row.team)
  const draftClass = next.prospects.length >= 30 ? next.prospects : generateDraftClass(2026 + endingSeason)
  draftClass.slice(0,30).forEach((prospect,index) => { const pick = index + 1; const team = order[index] ?? teams[index].abbr; const rookie = makeRookie(prospect, endingSeason, pick, team); next.generatedPlayers.push(rookie); const model = createPlayerModel(rookie); model.age = prospect.age; model.archetype = prospect.archetype; model.phase = 'development'; model.hiddenPotential = Math.min(96, rookie.overall + 5 + (pick % 9)); next.playerModels[rookie.id] = model; next.economy.contracts[rookie.id] = {playerId:rookie.id,team,salary:Math.max(1_200_000,12_000_000-pick*310_000),years:4,startSeason:`${2025+endingSeason}-${String(26+endingSeason).slice(-2)}`,option:'team',status:'active',source:'SIMULATION'}; next.health[rookie.id] = {fatigue:10,condition:96}; next.draftHistory.push({season:endingSeason,pick,team,playerId:rookie.id,name:rookie.name,position:rookie.position}) })
  const allPlayers = [...players,...next.generatedPlayers].filter((player) => !next.retiredPlayerIds.includes(player.id)); const quality = (player: Player) => { const model = next.playerModels[player.id]; return (model?.offense ?? player.overall) + (model?.defense ?? player.overall) + (model?.hiddenPotential ?? player.overall) * .3 }
  for (const team of teams) { let active = allPlayers.filter((player) => next.economy.contracts[player.id]?.team === team.abbr && next.economy.contracts[player.id]?.status === 'active').sort((a,b) => quality(b)-quality(a)); for (const cut of active.slice(18)) { const contract = next.economy.contracts[cut.id]; contract.status = 'waived'; contract.team = 'FA'; contract.years = 0 } active = active.slice(0,18); const freeAgents = allPlayers.filter((player) => next.economy.contracts[player.id]?.status !== 'active').sort((a,b) => quality(b)-quality(a)); while (active.length < 15 && freeAgents.length) { const signing = freeAgents.shift()!; const contract = next.economy.contracts[signing.id]; contract.team = team.abbr; contract.status = 'active'; contract.years = 1 + ((signing.id + endingSeason) % 3); contract.salary = Math.max(1_200_000,Math.round((signing.overall - 55) ** 2 * 33_000)); contract.startSeason = `${2025+endingSeason}-${String(26+endingSeason).slice(-2)}`; active.push(signing) } }
  next.seasonNumber += 1; next.fixtures = createLeagueSchedule(teams, next.seasonNumber); next.standings = baseStandings(teams); next.playerStats = Object.fromEntries(Object.keys(next.playerModels).map((id) => [Number(id), blankStats()])); next.results = {}; next.playoffs = []; next.record = {wins:0,losses:0}; next.prospects = generateDraftClass(2026 + next.seasonNumber); next.currentDate = `${2025 + next.seasonNumber}-10-20`; next.rotation = allPlayers.filter((player) => next.economy.contracts[player.id]?.team === next.teamAbbr && next.economy.contracts[player.id]?.status === 'active').sort((a,b) => quality(b)-quality(a)).slice(0,10).map((player,index) => ({playerId:player.id,minutes:[34,33,31,29,27,23,20,16,15,12][index],role:index<5?'Starter':index<9?'Rotation':'Reserve'})); next.news.unshift({id:`draft-${endingSeason}`,date:next.currentDate,category:'league',title:`Draft e offseason ${endingSeason} concluídos`,body:`30 prospectos DEV selecionados; ${next.retiredPlayerIds.length} aposentadorias acumuladas e elencos equilibrados pela IA.`}); next.simulationLog.push(`Offseason ${endingSeason}: draft de 30 escolhas, agência livre, aposentadorias e entrada na temporada ${next.seasonNumber}.`); return next
}
